apiVersion: serving.knative.dev/v1
kind: Service
  meta
name: loadgen
namespace: default
spec:
  template:
    metadata:
    annotations:
      autoscaling.knative.dev/target: "5"
      autoscaling.knative.dev/minScale: "0"
      autoscaling.knative.dev/maxScale: "20"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
      networking.knative.dev/ingress.class: "kourier.ingress.networking.knative.dev"
    spec:
      containers:
        - image: alexpoostotel/loadgen-service:0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"