server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billing?currentSchema=public
    username: billing
    password: billing123
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    driver: "org.postgresql.Driver"
    url: jdbc:postgresql://billing-db:5432/billing?currentSchema=public
    user: billing
    password: billing123
    schemas: public
    default-schemas: public

prometheus:
  url: http://prometheus-operated.observability.svc:9090

billing:
  rates:
    per-call: 0.001          # ₽/вызов
    per-ms: 0.00001          # ₽/мс
    per-mb-sec: 0.000001     # ₽/МБ·сек
    cold-start-penalty: 0.1  # ₽/cold start